name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
    permissions:
      contents: read
      checks: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew check

      - name: Test Report
        if: (success() || failure())
        uses: dorny/test-reporter@v1
        with:
          name: Unit Test Results
          path: build/test-results/**/*.xml
          reporter: java-junit

      - name: Bump version and push tag
        if: success()
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''

      - name: Create a GitHub release
        if: success()
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

  build:
    name: Build on ${{ matrix.os }}
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            targets: "publishJvmPublicationToMavenCentralRepository publishLinuxX64PublicationToMavenCentralRepository publishLinuxArm64PublicationToMavenCentralRepository"
          - os: macos-latest
            targets: "publishIosX64PublicationToMavenCentralRepository publishIosArm64PublicationToMavenCentralRepository publishIosSimulatorArm64PublicationToMavenCentralRepository publishMacosX64PublicationToMavenCentralRepository publishMacosArm64PublicationToMavenCentralRepository"
          - os: windows-latest
            targets: "publishMingwX64PublicationToMavenCentralRepository"
    permissions:
      contents: write
      checks: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Update version in build.gradle.kts
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "macOS" ]]; then
            sed -i '' 's/version\.set(".*")/version.set("${{ needs.test.outputs.new_tag }}")/' build.gradle.kts
          else
            sed -i 's/version\.set(".*")/version.set("${{ needs.test.outputs.new_tag }}")/' build.gradle.kts
          fi

      - name: Setup signing key
        shell: bash
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 -d > signing.key
          echo "SIGNING_KEY=$(cat signing.key)" >> $GITHUB_ENV

      - name: Build targets for ${{ matrix.os }}
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: ${{ matrix.targets }}
        env:
          CENTRAL_PORTAL_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
          CENTRAL_PORTAL_PASSWORD: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

      - name: Cleanup signing key
        if: always()
        shell: bash
        run: rm -f signing.key
